/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package creatingpublishers;

import java.util.stream.IntStream;

import reactor.core.publisher.Flux;

public class App {

    public static void main(String[] args) {
        FluxSinkImpl fluxSinkImpl = new FluxSinkImpl();
        Flux<Integer> flux = Flux.create(fluxSinkImpl)
            .share();

        flux.subscribe(i -> System.out.println("Recibido: "+i));

        IntStream.range(0, 11)
            .forEach(fluxSinkImpl::publishElement);
    }

}
