/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projectreactor.mono;

import reactor.core.publisher.Mono;

public class Lec03MonoSubscribe {

    public static void main(String[] args) {
        Mono<String> mono = Mono.just("Pelota");

        mono
            .log()
            .subscribe(
                r -> System.out.println("Nomero recibido: " + r),
                e -> System.err.println("Error: "+ e.getMessage()),
                () -> System.out.println("Completed...")
            );
    }
}
